import Foundation

/// 업데이트 항목 하나. 아래에 딸린 세부가 있을 수 있다.
///
/// 큰 개편은 제목 한 줄로는 무엇이 바뀌었는지 알 수 없고, 세부를 같은 층에 늘어놓으면
/// 열 줄이 평평하게 이어져 어디까지가 한 덩이인지 읽히지 않는다.
struct ReleaseNoteItem: Sendable, Equatable {
    let text: String
    var details: [String] = []

    /// 제목과 세부를 합친 전체 문구. 번역 누락 검사가 한 줄씩 훑을 때 쓴다.
    var lines: [String] { [text] + details }
}

/// 한 업데이트에서 바뀐 것.
struct ReleaseNote: Identifiable, Sendable, Equatable {
    let version: String
    let items: [ReleaseNoteItem]
    var id: String { version }

    init(version: String, items: [ReleaseNoteItem]) {
        self.version = version
        self.items = items
    }

    /// 세부가 없는 목록. 예전 업데이트은 전부 이 모양이다.
    init(version: String, lines: [String]) {
        self.init(version: version, items: lines.map { ReleaseNoteItem(text: $0) })
    }
}

/// 업데이트 기록. 새 버전을 내기 전에 여기에 먼저 적는다 —
/// `ReleaseNotesTests` 가 배포 버전에 해당하는 항목이 없으면 실패시킨다.
///
/// 문구는 `L` 이 들고 있어 언어를 따라간다. 목록은 최신이 앞이다.
enum ReleaseNotes {
    /// 지금 돌고 있는 앱의 버전. 없으면 nil — 개발 빌드나 테스트 러너가 그렇다.
    static var runningVersion: String? {
        Bundle.main.object(forInfoDictionaryKey: "CFBundleShortVersionString") as? String
    }

    /// 버전을 숫자 묶음으로 바꾼다. 문자열 비교로는 0.3.10 이 0.3.2 보다 앞이 된다.
    static func ordering(_ version: String) -> [Int] {
        version.split(separator: ".").map { Int($0) ?? 0 }
    }

    /// 최신이 앞인가. 뒤엣것이 앞엣것보다 반드시 작아야 한다.
    static func isDescending(_ notes: [ReleaseNote]) -> Bool {
        zip(notes, notes.dropFirst()).allSatisfy {
            ordering($1.version).lexicographicallyPrecedes(ordering($0.version))
        }
    }
}

extension L {

    var releaseNotes: [ReleaseNote] {
        [
            ReleaseNote(version: "0.15.0", lines: [
                t("팩 뜯기 연출, 팩 검색과 키보드 조작을 추가했습니다.",
                  "Added pack tearing, pack search and keyboard controls.",
                  "パック開封演出、パック検索、キーボード操作を追加しました。",
                  "Añadimos apertura de sobres, búsqueda y controles de teclado.",
                  "Ajout de l’ouverture des boosters, de la recherche et des commandes clavier.",
                  "Adicionamos abertura de pacotes, busca e controles de teclado."),
                t("누적 개봉 수에 따른 트레이너 레벨·보상·칭호와 매일 바뀌는 8장 마켓을 추가했습니다.",
                  "Added trainer levels, rewards and titles based on lifetime openings, plus an eight-card daily market.",
                  "累計開封数によるトレーナーレベル、報酬、称号と、毎日更新される8枚のマーケットを追加しました。",
                  "Añadimos niveles, recompensas y títulos por sobres abiertos, y un mercado diario de ocho cartas.",
                  "Ajout de niveaux, récompenses et titres selon les ouvertures, et d’un marché quotidien de huit cartes.",
                  "Adicionamos níveis, recompensas e títulos por pacotes abertos, e um mercado diário de oito cartas."),
                t("친구가 교환할 수 있는 카드에서 제안하고 역제안으로 답할 수 있습니다.",
                  "Choose tradeable cards from a friend’s binder and answer with counter-offers.",
                  "フレンドの交換可能カードから提案し、対案で返信できます。",
                  "Elige cartas intercambiables de tus amigos y responde con contraofertas.",
                  "Choisissez les cartes échangeables d’un ami et répondez par une contre-offre.",
                  "Escolha cartas disponíveis dos amigos e responda com contrapropostas."),
                t("세트별 실측 봉입률과 도감 보상을 갱신했습니다. 온라인 플레이에는 앱 업데이트가 필요합니다.",
                  "Updated measured set-specific pull rates and dex rewards. Update the app to continue online play.",
                  "セットごとの実測封入率と図鑑報酬を更新しました。オンラインプレイにはアプリ更新が必要です。",
                  "Actualizamos tasas medidas por colección y recompensas. Actualiza la app para jugar en línea.",
                  "Mise à jour des taux mesurés et des récompenses du Pokédex. Mettez l’app à jour pour jouer en ligne.",
                  "Atualizamos taxas medidas por coleção e recompensas. Atualize o app para jogar online.")
            ]),
            ReleaseNote(version: "0.14.0", lines: [
                t("가입과 기존 계정 연결을 구분해 안내합니다. 초대 코드는 선택 사항이며, 붙여 넣은 코드 앞뒤의 공백을 제거합니다. 초대제 서버에는 필요한 코드를 안내합니다.",
                  "Clarified sign-up versus existing-account linking. Invitation codes are optional, pasted whitespace is trimmed, and invite-only servers show actionable code guidance.",
                  "新規登録と既存アカウント連携の案内を分けました。招待コードは任意で、貼り付けた前後の空白を除去し、招待制サーバーでは必要なコードを案内します。",
                  "Aclaramos el registro y la vinculación de cuentas. Los códigos son opcionales, se recortan espacios al pegar y los servidores con invitación muestran instrucciones.",
                  "L’inscription et la liaison de compte sont mieux expliquées. Les codes sont facultatifs, les espaces collés sont retirés et les serveurs sur invitation affichent les instructions.",
                  "Esclarecemos o cadastro e a vinculação de contas. Os códigos são opcionais, espaços colados são removidos e servidores por convite mostram orientações.")
            ]),
            ReleaseNote(version: "0.13.0", lines: [
                t("온라인 창·계정·오류 안내를 6개 언어로 지원하고, 교환 제안의 빈 카드 전송 문제를 수정했습니다. 바인더 카드를 시세순으로 고르고 끌어서 순서를 바꿀 수 있습니다.",
                  "Online views, accounts and errors now support six languages. Fixed empty trade proposals, added a value-sorted binder picker and drag-to-reorder.",
                  "オンライン画面・アカウント・エラー案内が6言語に対応しました。空の交換提案を修正し、価格順のバインダー選択とドラッグ並べ替えを追加しました。",
                  "Las vistas online, cuentas y errores admiten seis idiomas. Corregimos las propuestas vacías y añadimos selección por valor y reordenación del álbum.",
                  "Les vues en ligne, comptes et erreurs prennent en charge six langues. Les offres vides sont corrigées; le classeur se trie par valeur et par glisser-déposer.",
                  "As telas online, contas e erros agora oferecem seis idiomas. Corrigimos propostas vazias e adicionamos seleção por valor e reordenação do fichário."),
                t("키체인·시세 검증·온라인 저장을 백그라운드로 옮기고 상태 전체 대신 변경분을 받아 화면 멈춤과 전송량을 줄였습니다. 교환·친구 신청 알림을 메뉴바에서 확인하고 고정 인증서로 서명합니다.",
                  "Moved Keychain, price validation and online cache work off the main thread. Lightweight state patches reduce transfer and pauses; menu-bar badges show trade and friend requests, with stable certificate signing.",
                  "キーチェーン・相場検証・オンライン保存をバックグラウンドに移し、差分通信で転送量と停止時間を削減しました。メニューバーに交換・フレンド申請を表示し、固定証明書で署名します。",
                  "El llavero, la validación de precios y la caché se procesan en segundo plano. Los cambios de estado reducen las pausas y el tráfico; la barra muestra solicitudes y usamos firma estable.",
                  "Le trousseau, la validation des prix et le cache sont traités en arrière-plan. Les mises à jour partielles réduisent les pauses et le trafic; la barre affiche les demandes et la signature est stable.",
                  "O chaveiro, a validação de preços e o cache são processados em segundo plano. Atualizações parciais reduzem pausas e tráfego; a barra mostra solicitações e usamos assinatura estável."),
            ]),
            ReleaseNote(version: "0.12.0", lines: [
                t("온라인 마켓·교환·친구 창을 개편하고 요청 번호와 오류 안내를 추가했습니다. 판매 가격은 서버 상한 안에서 안전하게 변환합니다.",
                  "Redesigned the online marketplace, trades and friends with request IDs and clearer errors. Listing prices are safely converted within server limits.",
                  "オンラインのマーケット・交換・フレンド画面を刷新し、リクエスト番号とエラー案内を追加しました。販売価格はサーバー上限内で安全に変換します。",
                  "Renovamos el mercado, los intercambios y los amigos con identificadores de solicitud y errores más claros. Los precios respetan los límites del servidor.",
                  "Le marché, les échanges et les amis ont été repensés avec des identifiants de requête et des erreurs plus claires. Les prix respectent les limites du serveur.",
                  "Reformulamos o mercado, as trocas e os amigos com IDs de solicitação e erros mais claros. Os preços respeitam os limites do servidor."),
                t("컬렉션에서 이름·카드 번호 검색과 번호순 정렬을 사용할 수 있습니다. 새 통계 탭에서 개봉·보유·판매 기록을 확인합니다.",
                  "Search the collection by name or card number and sort by number. The new statistics tab shows openings, ownership and sales.",
                  "コレクションを名前・カード番号で検索し、番号順に並べ替えられます。新しい統計タブで開封・所持・売却の記録を確認できます。",
                  "Busca por nombre o número y ordena por número. La nueva pestaña de estadísticas muestra aperturas, cartas y ventas.",
                  "Recherchez par nom ou numéro et triez par numéro. Le nouvel onglet de statistiques affiche les ouvertures, la collection et les ventes.",
                  "Pesquise por nome ou número e ordene por número. A nova aba de estatísticas mostra aberturas, coleção e vendas."),
                t("개봉 결과를 가격순·레어도순으로 정렬하고 시세 기반 아우라를 추가했습니다. 카드 넘김 대기를 제거하고 30주년 에너지·ACE SPEC·리버스·금색 포일을 보완했습니다.",
                  "Sort opening results by value or rarity with price-aware reveal auras. Removed card-advance delays and corrected anniversary Energy, ACE SPEC, reverse and gold foil.",
                  "開封結果を価格・レア度順に並べ替え、相場に応じたオーラを追加しました。カード送りの待機を削除し、記念エネルギー・ACE SPEC・リバース・金色ホイルを修正しました。",
                  "Ordena los resultados por valor o rareza con auras según el precio. Eliminamos las pausas al avanzar y corregimos los acabados de Energía aniversario, ACE SPEC, reverso y dorado.",
                  "Triez les résultats par valeur ou rareté avec des auras liées au prix. Les pauses entre cartes ont été supprimées et les effets Énergie anniversaire, ACE SPEC, reverse et dorés corrigés.",
                  "Ordene os resultados por valor ou raridade com auras baseadas no preço. Removemos pausas entre cartas e corrigimos os efeitos de Energia comemorativa, ACE SPEC, reverso e dourado.")
            ]),
            ReleaseNote(version: "0.11.12", lines: [
                t("온라인 계정으로 여러 Mac의 카드·팩·재화를 공유하고 친구·교환·마켓을 사용할 수 있습니다. 초대 코드로 가입하며, 기존 세이브는 운영자와 이전한 뒤 연결합니다. 에너지 이미지를 포함한 모든 카드 그림은 CDN에서 받아 캐시합니다.",
                  "Online accounts share cards, packs and currency across Macs, with friends, trades and a marketplace. Register with an invitation code; existing saves must be migrated by the operator before linking. All card artwork, including Energy, is fetched from the CDN and cached.",
                  "オンラインアカウントでMac間のカード・パック・通貨を共有し、フレンド・交換・マーケットを利用できます。招待コードで登録し、既存セーブは運営による移行後に接続します。エネルギーを含む画像はCDNから取得します。",
                  "Las cuentas en línea comparten cartas, sobres y moneda entre Macs, con amigos, intercambios y mercado. Regístrate con un código; el operador debe migrar las partidas existentes antes de vincularlas. Todas las imágenes, incluidas Energía, se descargan del CDN.",
                  "Les comptes en ligne partagent cartes, boosters et monnaie entre Macs, avec amis, échanges et marché. Inscrivez-vous avec un code ; les sauvegardes existantes doivent être migrées par l’opérateur avant liaison. Toutes les images, Énergie comprise, viennent du CDN.",
                  "Contas online compartilham cartas, pacotes e moeda entre Macs, com amigos, trocas e mercado. Cadastre-se com um convite; o operador deve migrar os saves existentes antes da vinculação. Todas as imagens, incluindo Energia, vêm do CDN."),
                t("보유한 같은 세트의 팩 수만큼 개봉 수량을 직접 입력할 수 있습니다. 온라인 대량 개봉은 최대 1,000팩씩 확정하며, 중단되면 온라인 창의 작업 탭에서 이어갈 수 있습니다. 이미 완료된 묶음은 유지됩니다.",
                  "Enter how many owned packs to open from the same set. Online bulk opening commits up to 1,000 packs per chunk and can resume from the online window’s Jobs tab after interruption. Completed chunks are retained.",
                  "同じセットの所持パック数まで開封数を直接入力できます。オンライン一括開封は最大1,000パックずつ確定し、中断後はオンライン画面の作業タブから再開できます。完了分は保持されます。",
                  "Introduce cuántos sobres del mismo set quieres abrir, hasta los que posees. La apertura en línea confirma lotes de hasta 1.000 y puede reanudarse desde la pestaña de trabajos. Los lotes completados se conservan.",
                  "Saisissez le nombre de boosters possédés du même set à ouvrir. L’ouverture en ligne valide des lots de 1 000 au maximum et reprend depuis l’onglet des tâches après une interruption. Les lots terminés sont conservés.",
                  "Digite quantos pacotes do mesmo set deseja abrir, até a quantidade que possui. A abertura online confirma lotes de até 1.000 e pode ser retomada na aba de tarefas. Os lotes concluídos são preservados."),
                t("성장 중인 Codex 로그는 새로 추가된 부분만 읽어 60초 갱신 때 발생하던 CPU 급등을 줄였습니다. 홀로 카드는 포인터 입력을 화면 프레임 단위로 합치고, 개봉 중 가려진 다음 카드의 중복 홀로·후광 합성을 제거했습니다.",
                  "Growing Codex logs now parse only appended data, reducing CPU spikes during periodic refreshes. Holographic cards coalesce pointer input per display frame and no longer render duplicate foil and glow layers for the covered next card.",
                  "増加中のCodexログは追記部分だけを解析し、定期更新時のCPU急上昇を抑えました。ホログラムカードはポインター入力を画面フレーム単位にまとめ、開封中に隠れている次のカードの重複ホイル・発光合成を削除しました。",
                  "Los registros de Codex en crecimiento ahora analizan solo los datos añadidos, reduciendo los picos de CPU. Las cartas holográficas agrupan la entrada del puntero por fotograma y evitan efectos duplicados en la siguiente carta cubierta.",
                  "Les journaux Codex en croissance n’analysent désormais que les données ajoutées, réduisant les pics CPU. Les cartes holographiques regroupent les mouvements par image et évitent les effets dupliqués sur la carte suivante masquée.",
                  "Logs Codex em crescimento agora processam apenas os dados anexados, reduzindo picos de CPU. Cartas holográficas agrupam o ponteiro por quadro e evitam efeitos duplicados na próxima carta coberta."),
                t("도감에서 한국어·영문 카드 이름을 검색해 해당 카드가 들어간 조합과 세트를 바로 찾을 수 있습니다.",
                  "Search Korean or English card names in the dex to find every combo and set containing that card.",
                  "図鑑で韓国語・英語のカード名を検索し、そのカードを含む組み合わせとセットを探せます。",
                  "Busca nombres de cartas en coreano o inglés para encontrar cada combo y set que las contiene.",
                  "Recherchez les noms coréens ou anglais pour trouver chaque combinaison et set contenant la carte.",
                  "Busque nomes de cartas em coreano ou inglês para encontrar cada combinação e set que contém a carta."),
                t("Sun & Moon·Team Rocket Returns 리버스의 문양 반응을 강화하고, RBG/BWR 카드의 넓은 백색 반사를 줄여 그림과 글자가 가려지지 않도록 했습니다.",
                  "Strengthened Sun & Moon and Team Rocket Returns reverse motifs, and reduced the broad white return on RBG/BWR cards so artwork and text remain visible.",
                  "Sun & MoonとTeam Rocket Returnsのリバース模様を強化し、RBG/BWRカードの広い白反射を抑えて絵と文字を見やすくしました。",
                  "Reforzados los motivos reverse de Sun & Moon y Team Rocket Returns, y reducido el reflejo blanco amplio de las cartas RBG/BWR para conservar la ilustración y el texto.",
                  "Renforcement des motifs reverse Sun & Moon et Team Rocket Returns, et réduction du large reflet blanc des cartes RBG/BWR afin de préserver l’illustration et le texte.",
                  "Reforçados os padrões reverse de Sun & Moon e Team Rocket Returns, com redução do reflexo branco amplo nas cartas RBG/BWR para preservar a arte e o texto."),
            ]),
            ReleaseNote(version: "0.11.11", lines: [
                t("위젯 창을 400pt 폭·480pt 본문으로 줄였습니다. 상세 카드와 개봉 화면을 맞추고, 중복 카드 가격·판매 안내가 잘리지 않도록 했습니다. Generations RC 19종의 잘못된 새김 재질을 평활 포일로 수정하고 피카츄 RC29의 노란 테두리를 제외했습니다. 카드별 문양·반사 영역의 전체 실물 대조 완료를 뜻하지 않습니다.",
                  "Reduced the widget window to 400pt wide with a 480pt content area. Adapted detail/reveal cards and kept duplicate prices and sale actions accessible. Removed erroneous engraved relief from 19 Generations RC cards and excluded Pikachu RC29's yellow rim. Individual motif and foil-area verification remains incomplete.",
                  "ウィジェットを幅400pt・本文480ptに縮小。詳細・開封カードを調整し、重複価格と売却操作の切れを防止。Generations RC 19種の誤った凹凸を平滑ホイルに修正し、RC29の黄色い枠を除外。全カードの模様・反射領域の実物照合完了を意味しません。",
                  "Ventana de 400pt y contenido de 480pt, con cartas adaptables y precios y ventas accesibles. Corregido el relieve erróneo de 19 cartas Generations RC y excluido el borde amarillo de RC29. La revisión física individual sigue incompleta.",
                  "Fenêtre de 400pt et contenu de 480pt, cartes adaptées et prix et ventes accessibles. Relief erroné retiré de 19 cartes Generations RC et bord jaune de RC29 exclu. La vérification physique individuelle reste incomplète.",
                  "Janela de 400pt e conteúdo de 480pt, com cartas adaptáveis e preços e vendas acessíveis. Removido o relevo incorreto de 19 cartas Generations RC e excluída a borda amarela de RC29. A verificação física individual continua incompleta."),
                t("카드·팩 원본을 앱에서 분리하고 CloudFront에서 저화질·고화질 이미지를 필요한 때 받아 캐시하도록 변경했습니다. 팝오버에 종료 버튼과 ⌘Q 단축키도 추가했습니다.",
                  "Moved card and pack originals out of the app. Low- and high-resolution artwork is now fetched from CloudFront on demand and cached locally. Added a visible Quit button and Command-Q shortcut.",
                  "カード・パック原画をアプリから分離し、低・高解像度画像をCloudFrontから必要時に取得してキャッシュします。終了ボタンと⌘Qも追加しました。",
                  "Las imágenes originales ya no se incluyen en la app; las versiones de baja y alta resolución se descargan de CloudFront y se guardan en caché. Añadidos Salir y ⌘Q.",
                  "Les images originales ne sont plus intégrées ; les versions basse et haute résolution viennent de CloudFront et sont mises en cache. Ajout d'un bouton Quitter et de ⌘Q.",
                  "As imagens originais saíram do app; versões de baixa e alta resolução vêm do CloudFront e ficam em cache. Adicionados Sair e ⌘Q."),
            ]),
            ReleaseNote(version: "0.11.10", lines: [
                t("30주년 복각 30종의 금박·배경·피사체를 개별 등록하고, 피카츄의 남은 방사형 무늬와 루기아의 넓은 금색 테두리를 보완했습니다. 일반 ex의 별무늬를 복원하고, 균열형 12종에 원본 경계에 고정된 반사를 추가했습니다. Ascended 리버스 무늬 8종의 누락도 채웠습니다. 실물 자료 기반 근사이며 전 카드 제조 원판의 일치를 보증하지 않습니다.",
                  "Registered separate gold, background and subject regions for all 30 Classic cards; completed missing Pikachu fans and Lugia's wide gold frame. Restored ordinary ex stars, added source-bound reflections for 12 cracked-ice cards, and supplied 8 missing Ascended reverse registrations. Reference-guided approximations, not certification of every factory plate.",
                  "30種の復刻カードの金箔・背景・対象領域を個別登録し、ピカチュウの放射模様とルギアの広い金枠を補完。通常exの星模様、12種の固定破片反射、8種のリバース模様を追加。資料に基づく近似であり製造原版の一致を保証しません。",
                  "Registradas regiones individuales de las 30 cartas Classic, abanicos de Pikachu y marco ancho de Lugia. Restauradas estrellas de ex, reflejos fijos en 12 cartas y 8 registros reverse ausentes. Aproximaciones basadas en referencias, no certificación de matrices.",
                  "Régions individuelles des 30 cartes Classic, éventails de Pikachu et large bordure de Lugia corrigés. Étoiles ex restaurées, reflets fixes sur 12 cartes et 8 motifs reverse manquants ajoutés. Approximations documentées, sans certification des matrices.",
                  "Registradas regiões individuais das 30 cartas Classic, leques de Pikachu e borda larga de Lugia. Restauradas estrelas ex, reflexos fixos em 12 cartas e 8 registros reverse ausentes. Aproximações baseadas em referências, não certificação de matrizes."),
            ]),
            ReleaseNote(version: "0.11.9", lines: [
                t("개별 사진을 검토한 57판형에 테두리·로고·배경 파편·피사체 요철을 분리 적용했습니다. 25주년 종이 테두리와 30주년 금박을 구분하고, 반사 누출과 큰 사각 패치를 보정했습니다. 미확인 영역은 기존 효과를 유지하며, 전체 카드나 제조 원판의 재현 완료를 의미하지 않습니다. 소장 기록·이미지·시세는 유지합니다.",
                  "Separated borders, logos, background fragments and subject microrelief for 57 individually photo-reviewed printings. Distinguished 25th paper borders from 30th gold foil and corrected reflection leaks and coarse patches. Unresolved areas keep their previous effects; this does not certify every card or factory plate. Collections, art and prices are preserved.",
                  "個別写真を確認した57仕様で枠・ロゴ・背景片・対象の微細凹凸を分離。25周年の紙枠と30周年の金箔を区別し、反射の漏れと大きな四角を修正。未確認領域は従来の効果を維持し、全カードや製造原版の再現完了を意味しません。所持記録・画像・価格は維持します。",
                  "Separados bordes, logotipos, fragmentos y microrrelieve en 57 variantes revisadas con fotos individuales. Diferenciados papel del 25.º y foil dorado del 30.º aniversario. Corregidas fugas y parches gruesos. Áreas sin confirmar conservan efectos anteriores; no certifica todas las cartas ni matrices. Colecciones, imágenes y precios preservados.",
                  "Séparation des bordures, logos, fragments et microreliefs de 57 variantes examinées sur photos individuelles. Distinction du papier du 25e et de la dorure du 30e anniversaire, correction des débordements et gros carrés. Zones non confirmées inchangées ; aucune certification de toutes les cartes ou matrices. Collections, images et prix conservés.",
                  "Separadas bordas, logotipos, fragmentos e microrrelevo em 57 variantes revisadas em fotos individuais. Diferenciados papel do 25º e folha dourada do 30º aniversário; corrigidos vazamentos e blocos grandes. Áreas não confirmadas mantêm efeitos anteriores; não certifica todas as cartas nem matrizes. Coleções, imagens e preços preservados."),
            ]),
            ReleaseNote(version: "0.11.8", lines: [
                t("작은 기울기에서 약했던 SAR·금색·어메이징 레어·메가어택·리버스 등의 반사 대비를 보완했습니다. 델타종은 사선 대신 대상 영역의 색 반사를 사용하고 Cosmos 배경과 미세 반짝임을 강화했습니다. 실물 기반 근사이며 기존 소장 기록·이미지·시세는 유지합니다.",
                  "Strengthened weak small-angle foil responses in SAR, gold, Amazing Rare, Mega Attack and reverse cards. Delta foil now reflects within its registered subjects instead of drawn bars; Cosmos background and microhighlights are clearer. Physical-card approximations; collections, art and prices preserved.",
                  "小さな傾きで弱かったSAR・金色・アメイジングレア・メガアタック・リバースの反射を調整。δは斜線ではなく対象領域の色反射を使用し、Cosmos背景と微細な輝きを強化。実物に基づく近似で、所持記録・画像・価格は維持します。",
                  "Reforzados los reflejos débiles de SAR, doradas, Amazing Rare, Mega Attack y reversas con inclinaciones pequeñas. Delta refleja en sus áreas registradas, sin bandas dibujadas; mejorados Cosmos y destellos finos. Aproximación física; colección, imágenes y precios conservados.",
                  "Renforcement des reflets faibles à petite inclinaison pour SAR, dorées, Amazing Rare, Mega Attack et reverses. Delta utilise ses zones enregistrées sans bandes dessinées ; Cosmos et microreflets renforcés. Approximation physique ; collections, images et prix conservés.",
                  "Reforçados reflexos fracos em pequenas inclinações de SAR, douradas, Amazing Rare, Mega Attack e reversas. Delta reflete nas áreas registradas sem faixas desenhadas; Cosmos e microbrilhos reforçados. Aproximação física; coleções, imagens e preços preservados."),
            ]),
            ReleaseNote(version: "0.11.7", lines: [
                t("일반 홀로·풀아트 엠보싱·Cosmos·입체 몬스터볼의 반사를 분리했습니다. 굵은 사선·흰 원·긁힌 듯한 입자를 줄이고 각도별 미세 반사를 보완했습니다. 실물 사진 기반 근사이며 제조 원판의 정밀 복제는 아닙니다. 기존 소장 기록·이미지·시세는 유지합니다.",
                  "Separated smooth holo, etched full art, Cosmos and 3D Ball optics. Reduced artificial bars, white rings and scratch-like facets; refined angular highlights. Photo-guided approximations, not factory-plate replicas. Collections, art and prices are preserved.",
                  "通常ホロ・フルアートの凹凸・Cosmos・立体ボールの反射を分離。人工的な斜線・白い輪・傷状の粒子を減らし、角度による微細反射を調整。実物写真に基づく近似で、製造原版の精密複製ではありません。所持記録・画像・価格は維持します。",
                  "Separadas las ópticas holo lisa, relieve, Cosmos y bolas 3D. Reducidas barras artificiales, anillos blancos y facetas como arañazos. Aproximaciones fotográficas, no réplicas de fábrica. Colecciones, imágenes y precios preservados.",
                  "Séparation des reflets holo lisses, gravés, Cosmos et des sphères 3D. Réduction des bandes artificielles, anneaux blancs et facettes rayées. Approximations photographiques, non des copies des matrices d’usine. Collections, images et prix préservés.",
                  "Separadas as ópticas holo lisa, gravada, Cosmos e esferas 3D. Reduzidas faixas artificiais, anéis brancos e facetas riscadas. Aproximações fotográficas, não réplicas das matrizes de fábrica. Coleções, imagens e preços preservados."),
            ]),
            ReleaseNote(version: "0.11.6", lines: [
                t("SAR의 거친 색 조각과 인위적인 소용돌이를 줄이고, 금색 카드의 미세 반사를 조정했습니다. Neo Shining 8종의 무지개 사선을 피사체 전용 은회색 입자로 교체했습니다. 실물 엠보싱의 정밀 복제는 아니며 기존 홀로 영역·소장 기록은 유지합니다.",
                  "Refined SAR microrelief and gold grain; replaced rainbow stripes on eight Neo Shining cards with subject-only silver grain. This is not a measured factory emboss replica. Foil masks and collections are preserved.",
                  "SARの微細な凹凸と金色の粒子を調整。Neo Shining 8種の虹色の斜線を対象部分のみの銀色粒子に変更。工場のエンボスの精密複製ではなく、ホロ領域と所持記録は維持します。",
                  "Ajustados el microrrelieve SAR y el grano dorado; franjas arcoíris de ocho Neo Shining sustituidas por grano plateado solo en el sujeto. No es una réplica del relieve de fábrica. Máscaras y colecciones preservadas.",
                  "Affinement du microrelief SAR et du grain doré ; remplacement des rayures arc-en-ciel de huit Neo Shining par un grain argenté limité au sujet. Pas une reproduction mesurée du relief d’usine. Masques et collections préservés.",
                  "Refinados o microrrelevo SAR e o grão dourado; listras arco-íris de oito Neo Shining substituídas por grão prateado apenas no tema. Não é uma réplica medida do relevo de fábrica. Máscaras e coleções preservadas."),
            ]),
            ReleaseNote(version: "0.11.5", lines: [
                t("새 확장팩·별도 컬렉션 1,283장의 한국어 카드 이름을 보완했습니다. 기존 이미지·홀로·시세·소장 기록은 유지하고, 이름이 누락되면 패키징 검사가 실패하도록 했습니다.",
                  "Added Korean names for 1,283 cards in new expansions and subsets. Images, foil, prices and collections are unchanged. Packaging now checks name coverage.",
                  "新拡張・サブセット1,283枚の韓国語名を補完。画像・ホロ・価格・所持記録は維持し、梱包時に名前の欠落を検査します。",
                  "Añadidos nombres coreanos para 1.283 cartas nuevas. Imágenes, efectos, precios y colecciones sin cambios; comprobación de nombres al empaquetar.",
                  "Ajout des noms coréens de 1 283 cartes. Images, effets, prix et collections inchangés ; contrôle des noms lors du packaging.",
                  "Adicionados nomes coreanos para 1.283 cartas. Imagens, efeitos, preços e coleções preservados; verificação de nomes no empacotamento."),
            ]),
            ReleaseNote(version: "0.11.4", lines: [
                t("30주년 뮤 RGB 3종에 출처가 명시된 실거래 기반 참고가를 추가했습니다. 카드·판형·팩 시세를 갱신하고 문자형 번호, 복각 번호와 미러 판형의 가격 연결을 수정했습니다. 조회되지 않은 기존 시세는 기준일과 함께 유지합니다.",
                  "Added sourced completed-sales estimates for all three 30th Mew RGB cards. Refreshed card, printing and pack quotes; fixed lettered numbers, reprint identities and parallel pricing. Unavailable quotes retain their previous values and dates.",
                  "30周年ミュウRGB3種に出典付き成約価格参考値を追加。カード・仕様別・パック相場を更新し、文字番号・復刻番号・ミラーの価格対応を修正。未取得価格は旧値と日付を維持します。",
                  "Añadidas estimaciones con fuente para los tres Mew RGB del 30.º aniversario. Actualizados precios de cartas, variantes y sobres. Corregidos números alfabéticos, reediciones y paralelas. Se conservan precios y fechas no disponibles.",
                  "Ajout d’estimations sourcées pour les trois Mew RGB du 30e anniversaire. Prix des cartes, variantes et boosters actualisés ; correction des numéros alphabétiques, rééditions et parallèles. Anciens prix et dates conservés si indisponibles.",
                  "Adicionadas estimativas com fonte para os três Mew RGB do 30º aniversário. Preços de cartas, variantes e pacotes atualizados; corrigidos números alfabéticos, reedições e paralelas. Valores indisponíveis mantêm preços e datas anteriores."),
            ]),
            ReleaseNote(version: "0.11.3", lines: [
                t("금색 뮤·풀아트 피카츄의 재질과 영역을 수정하고, Neo Shining·δ 카드의 반사를 포켓몬과 해당 테두리로 제한했습니다. VSTAR·샤이니 풀아트 106종에 계열별 미세 요철을 추가했습니다. 기존 소장 기록은 유지됩니다.",
                  "Corrected gold Mew and full-art Pikachu optics, restricted Neo Shining and delta foil to the subject and applicable frame, and added distinct microrelief to 106 VSTAR and Shiny full-art printings. Existing collection records are preserved.",
                  "金色ミュウとフルアートのピカチュウの質感・領域を修正。Neo Shining・δの反射を対象と該当枠に限定し、VSTAR・色違いフルアート106種に系統別の微細な凹凸を追加。所持記録は維持されます。",
                  "Corregidos Mew dorado y Pikachu de arte completo. Reflejos Neo Shining y delta limitados al sujeto y marco correspondiente; microrelieve diferenciado en 106 variantes VSTAR y Shiny. Se conservan las colecciones.",
                  "Correction des effets de Mew doré et Pikachu pleine illustration. Reflets Neo Shining et delta limités au sujet et au cadre concerné ; microrelief distinct pour 106 variantes VSTAR et Shiny. Collections préservées.",
                  "Corrigidos os efeitos de Mew dourado e Pikachu de arte completa. Reflexos Neo Shining e delta limitados ao tema e à moldura adequada; microrrelevo distinto em 106 variantes VSTAR e Shiny. Coleções preservadas."),
            ]),
            ReleaseNote(version: "0.11.2", lines: [
                t("30주년 복각의 금색 테두리, 피카츄 불꽃 홀로, FUR·RGB 표면과 메가ex 텍스처를 분리했습니다. Ascended Heroes의 카드별 에너지·볼·로켓단 미러 280종도 반영했습니다.",
                  "Separated 30th gold reprint borders, Pikachu fireworks, FUR/RGB surfaces and Mega ex texture. Added 280 card-specific Ascended Heroes energy, Ball and Team Rocket mirrors.",
                  "30周年復刻の金枠、ピカチュウの花火ホロ、FUR・RGB表面、メガexの質感を分離。Ascended Heroesのエネルギー・ボール・ロケット団ミラー280種も反映。",
                  "Separados los bordes dorados del 30 aniversario, fuegos de Pikachu, superficies FUR/RGB y textura Mega ex. Añadidas 280 variantes espejo de Ascended Heroes.",
                  "Séparation des cadres dorés du 30e anniversaire, feux de Pikachu, surfaces FUR/RGB et texture Méga-ex. Ajout de 280 variantes miroir d’Ascended Heroes.",
                  "Separados os contornos dourados do 30º aniversário, fogos de Pikachu, superfícies FUR/RGB e textura Mega ex. Adicionadas 280 variantes espelhadas de Ascended Heroes."),
            ]),
            ReleaseNote(version: "0.11.1", lines: [
                t("홀로 영역을 카드별 원본 이미지 좌표에 맞췄습니다. 30주년·복각 프레임, e-Reader 곡선과 메가어택 글자 위치를 보정했습니다.",
                  "Foil regions now follow each original scan. Corrected anniversary/reprint frames, e-Reader curves and Mega Attack lettering.",
                  "ホイル領域を各原本の座標に整合。記念・復刻枠、e-Readerの曲線、メガアタックの文字位置を修正。",
                  "Regiones foil alineadas con cada original. Corregidos marcos de aniversario y reediciones, curvas e-Reader y letras Mega Attack.",
                  "Zones brillantes alignées sur chaque original. Cadres anniversaire et rééditions, courbes e-Reader et lettres Mega Attack corrigés.",
                  "Regiões foil alinhadas a cada original. Corrigidos quadros de aniversário e reedições, curvas e-Reader e letras Mega Attack."),
            ]),
            ReleaseNote(version: "0.11.0", lines: [
                t("30th Celebration까지 최신 영문 팩 5종과 카드 852장을 추가했습니다. 30주년 팩은 피카츄 1장 포함 홀로 5장 구성입니다.",
                  "Five English expansions and 852 cards through 30th Celebration. Anniversary packs contain five foil cards, including one Pikachu Rare.",
                  "30th Celebrationまで英語版5拡張・852枚を追加。記念パックはピカチュウ1枚を含むホイル5枚。",
                  "Cinco expansiones y 852 cartas hasta 30th Celebration. Cinco cartas foil, incluido un Pikachu Rare, por sobre de aniversario.",
                  "Cinq extensions et 852 cartes jusqu'à 30th Celebration. Cinq cartes brillantes dont un Pikachu Rare par booster anniversaire.",
                  "Cinco expansões e 852 cartas até 30th Celebration. Cinco cartas foil, incluindo um Pikachu Rare, por pacote de aniversário."),
                t("고해상도 카드 원본을 앱에 저장해 오프라인으로 표시합니다. 작은 캐시 이미지가 상세 화면에 고정되던 문제를 수정했습니다.",
                  "Original HD card art is installed for offline use. Detail views now upgrade cached thumbnails to full-resolution scans.",
                  "高解像度の原本をオフライン用に同梱。詳細表示が小さなキャッシュ画像のままになる不具合を修正。",
                  "Imágenes originales HD sin conexión. La vista detallada sustituye miniaturas en caché por imágenes de alta resolución.",
                  "Images HD originales hors ligne. Les détails remplacent les miniatures en cache par les scans haute résolution.",
                  "Imagens HD originais offline. A visualização detalhada substitui miniaturas em cache por imagens de alta resolução."),
            ]),
            ReleaseNote(version: "0.10.0", lines: [
                t("구매·개봉·오리파를 한 번에 저장하고 실패 시 취소합니다. 정상 세이브 8개를 보관합니다.",
                  "Atomic purchases, openings and Oripa with rollback and eight valid save backups.",
                  "購入・開封・オリパを一括保存。失敗時は取消、正常バックアップ8個を保持。",
                  "Compras y aperturas atómicas con reversión y ocho copias válidas.",
                  "Achats et ouvertures atomiques avec annulation et huit sauvegardes valides.",
                  "Compras e aberturas atômicas com reversão e oito backups válidos."),
                t("판형별 시세를 확대하고 시장가와 게임 보정 가격을 구분합니다. 설정에서 시세 파일을 가져올 수 있습니다.",
                  "Expanded printing prices, separate market/game pricing and explicit snapshot import in Settings.",
                  "印刷別相場を拡充、市場価格とゲーム価格を区別。設定から価格データを取込可能。",
                  "Más precios por acabado, mercado/juego separados e importación de datos en Ajustes.",
                  "Plus de prix par finition, marché/jeu distincts et importation dans Réglages.",
                  "Mais preços por acabamento, mercado/jogo separados e importação em Ajustes."),
                t("실물 구성 모드·재현 가능한 개봉 이력·프리즈마틱 3 SIR 특수팩을 추가했습니다. 미공개 확률은 추정치입니다.",
                  "Physical-model mode, replayable opening history and Prismatic three-SIR packs. Unpublished odds remain estimates.",
                  "実物モデル、再現可能な開封履歴、Prismatic 3 SIRを追加。非公開確率は推定。",
                  "Modelo físico, historial reproducible y Prismatic de tres SIR. Tasas no publicadas estimadas.",
                  "Modèle physique, historique rejouable et Prismatic trois SIR. Taux non publiés estimés.",
                  "Modelo físico, histórico reproduzível e Prismatic de três SIR. Taxas não publicadas estimadas."),
                t("이미지 기반 국소 식각·Shining Legends 포켓몬 마스크를 적용하고 원본 자동 업데이트를 차단했습니다.",
                  "Image-guided local foil relief, Shining Legends subject masks and protected local-custom updates.",
                  "画像に沿う局所エッチングとShining Legends輪郭マスク、ローカル版更新保護。",
                  "Relieve local según imagen, máscaras Shining Legends y protección de actualizaciones locales.",
                  "Relief local guidé par l'image, masques Shining Legends et mises à jour locales protégées.",
                  "Relevo local guiado pela imagem, máscaras Shining Legends e proteção de atualizações locais."),
            ]),
            ReleaseNote(version: "0.9.4", items: [
                ReleaseNoteItem(text: t("실물 레퍼런스 기반 홀로그램 재질 전면 보정",
                                         "Reference-based overhaul of physical hologram materials",
                                         "実物資料に基づくホログラム素材の全面調整",
                                         "Revisión integral de materiales holográficos basada en referencias reales",
                                         "Révision complète des matériaux holographiques d'après des références réelles",
                                         "Revisão completa dos materiais holográficos com base em referências reais"), details: [
                    t("SAR·MUR·BWR·Radiant·Amazing·Prism·VMAX·VSTAR를 서로 다른 광학 재질로 분리",
                      "Separated SAR, MUR, BWR, Radiant, Amazing, Prism, VMAX and VSTAR into distinct optical materials",
                      "SAR・MUR・BWR・Radiant・Amazing・Prism・VMAX・VSTARを異なる光学素材として分離",
                      "SAR, MUR, BWR, Radiant, Amazing, Prism, VMAX y VSTAR usan materiales ópticos distintos",
                      "SAR, MUR, BWR, Radiant, Amazing, Prism, VMAX et VSTAR utilisent des matériaux optiques distincts",
                      "SAR, MUR, BWR, Radiant, Amazing, Prism, VMAX e VSTAR agora usam materiais ópticos distintos"),
                    t("18,097장 카드의 타입·Trainer·Energy·Tera 메타데이터로 세대별 리버스 홀로 문양 적용",
                      "Applied era-specific reverse-holo motifs from type, Trainer, Energy and Tera metadata for 18,097 cards",
                      "18,097枚のタイプ・Trainer・Energy・Tera情報から世代別リバースホロ模様を適用",
                      "Patrones reverse por época basados en metadatos de tipo, Trainer, Energy y Tera para 18.097 cartas",
                      "Motifs reverse par époque basés sur les métadonnées de type, Trainer, Energy et Tera de 18 097 cartes",
                      "Padrões reverse por era com metadados de tipo, Trainer, Energy e Tera para 18.097 cartas"),
                    t("카드에 고정된 식각과 이동하는 반사광을 분리하고 흰 번짐을 줄여 그림 가독성 유지",
                      "Separated card-fixed etching from moving reflections and reduced white wash to preserve artwork",
                      "カード固定のエッチングと動く反射光を分離し、白飛びを抑えて絵柄を保持",
                      "Se separó el grabado fijo del reflejo móvil y se redujo el brillo blanco para conservar la ilustración",
                      "La gravure fixe est séparée du reflet mobile et l'éblouissement blanc réduit pour préserver l'illustration",
                      "A gravação fixa foi separada do reflexo móvel e o brilho branco reduzido para preservar a arte"),
                ]),
            ]),
            ReleaseNote(version: "0.9.3", items: [
                ReleaseNoteItem(text: t("SAR 홀로그램 대비와 식각 강화",
                                         "Stronger SAR hologram contrast and etching",
                                         "SARホログラムのコントラストとエッチングを強化",
                                         "Mayor contraste y grabado holográfico para SAR",
                                         "Contraste et gravure holographiques SAR renforcés",
                                         "Maior contraste e gravação holográfica para SAR"), details: [
                    t("IR과 공유하던 새틴 재질 대신 카드별 윤곽 식각과 글리터 포일 적용",
                      "Replaced the shared IR satin with card-seeded contour etching and glitter foil",
                      "IR共通のサテン素材を、カード別の輪郭エッチングとグリッターフォイルに変更",
                      "El satén compartido con IR se sustituyó por grabado de contorno y foil brillante por carta",
                      "Le satin partagé avec les IR est remplacé par une gravure de contour et un foil scintillant propres à chaque carte",
                      "O cetim compartilhado com IR foi substituído por gravação de contorno e foil brilhante por carta"),
                    t("흰 반사광은 유지·감소하고 기울일 때 색 이동과 미세무늬만 더 선명하게 조정",
                      "Kept white glare restrained while making tilt-driven color shift and microtexture clearer",
                      "白い反射光を抑えたまま、傾けた時の色変化と微細模様を鮮明化",
                      "Se mantuvo bajo el reflejo blanco y se acentuaron el cambio de color y la microtextura al inclinar",
                      "Le reflet blanc reste contenu tandis que le changement de couleur et la microtexture gagnent en netteté à l'inclinaison",
                      "O reflexo branco permaneceu contido, com mudança de cor e microtextura mais nítidas ao inclinar"),
                ]),
            ]),
            ReleaseNote(version: "0.9.2", items: [
                ReleaseNoteItem(text: t("세트·판형별 실물 홀로그램 재질 적용",
                                         "Physical hologram materials by set and printing",
                                         "セット・仕様別の実物ホログラム素材を適用",
                                         "Materiales holográficos físicos según colección y acabado",
                                         "Matériaux holographiques physiques selon la série et la finition",
                                         "Materiais holográficos físicos por coleção e acabamento"), details: [
                    t("시대별 기본·리버스 홀로와 특수 판형을 각각 다른 방향·무늬·범위로 표현",
                      "Era holos, reverse sheets and special printings now use distinct direction, motif and coverage",
                      "時代別ホロ・リバース・特別仕様を、それぞれ異なる方向・模様・範囲で表現",
                      "Los holos por era, reversos y acabados especiales usan dirección, motivo y cobertura propios",
                      "Les holos par époque, reverses et finitions spéciales ont chacun leur direction, motif et zone",
                      "Holos por era, reversos e acabamentos especiais usam direção, motivo e área próprios"),
                    t("흰색 반사광을 낮추고 무늬 대비를 살려 카드 그림이 가려지지 않도록 조정",
                      "Reduced white glare while preserving pattern contrast so the artwork stays visible",
                      "白い反射光を抑えつつ模様のコントラストを保ち、イラストを見やすく調整",
                      "Menos reflejo blanco y más contraste de patrón para mantener visible la ilustración",
                      "Reflet blanc réduit et contraste des motifs préservé pour garder l'illustration visible",
                      "Reflexo branco reduzido e contraste dos padrões preservado para manter a arte visível"),
                    t("MUR 금색 식각, ACE 다이아몬드, BREAK 격자, Prism·Shining·고전 예외 분리",
                      "Separated MUR gold etching, ACE diamonds, BREAK grid, Prism, Shining and vintage exceptions",
                      "MUR金色エッチング、ACEダイヤ、BREAK格子、Prism・Shining・旧作例外を分離",
                      "Separados el grabado dorado MUR, diamantes ACE, rejilla BREAK, Prism, Shining y excepciones clásicas",
                      "Séparation de la gravure dorée MUR, des losanges ACE, de la grille BREAK, Prism, Shining et exceptions rétro",
                      "Separados gravação dourada MUR, losangos ACE, grade BREAK, Prism, Shining e exceções clássicas"),
                ]),
            ]),
            ReleaseNote(version: "0.9.1", items: [
                ReleaseNoteItem(text: t("MUR 홀로그램을 금색 재질로 수정",
                                         "Corrected MUR holograms to a gold finish",
                                         "MURのホログラムを金色の質感に修正",
                                         "Hologramas MUR corregidos a un acabado dorado",
                                         "Hologrammes MUR corrigés avec une finition dorée",
                                         "Hologramas MUR corrigidos para acabamento dourado"), details: [
                    t("메가어택의 무지개 버스트와 분리해 금색 식각과 테두리 적용",
                      "Separated from Mega Attack's rainbow burst with gold etching and border",
                      "メガアタックの虹色バーストと分離し、金色のエッチングと枠を適用",
                      "Separados del destello arcoíris de Mega Attack con grabado y borde dorados",
                      "Séparés de l'éclat arc-en-ciel Mega Attack avec gravure et bordure dorées",
                      "Separados do brilho arco-íris de Mega Attack com gravação e borda douradas"),
                ]),
            ]),
            ReleaseNote(version: "0.9.0", items: [
                ReleaseNoteItem(text: t("실물 팩 구성을 세트별로 반영",
                                         "Set-specific physical pack layouts",
                                         "セット別の実物パック構成を反映",
                                         "Composición física por colección",
                                         "Composition physique selon la série",
                                         "Composição física por coleção"), details: [
                    t("시대별 카드 장수 · 특수 서브셋 · 실제 사례가 있는 특수팩 적용",
                      "Era card counts, special subsets and documented special packs",
                      "時代別の枚数・特別サブセット・実例のある特別パックを適用",
                      "Cantidad por era, subconjuntos y sobres especiales documentados",
                      "Quantités par époque, sous-ensembles et boosters spéciaux documentés",
                      "Quantidade por era, subconjuntos e pacotes especiais documentados"),
                ]),
                ReleaseNoteItem(text: t("팩과 특수 판형에 시장 시세 적용",
                                         "Market prices for packs and special printings",
                                         "パックと特別仕様に市場価格を適用",
                                         "Precios de mercado para sobres y acabados especiales",
                                         "Prix du marché pour boosters et finitions spéciales",
                                         "Preços de mercado para pacotes e acabamentos especiais"), details: [
                    t("밀봉팩 시세와 카드 기대값 하한을 함께 사용",
                      "Uses sealed-pack quotes with an expected-card-value floor",
                      "未開封パック相場とカード期待値の下限を併用",
                      "Combina la cotización del sobre sellado con un mínimo por valor esperado",
                      "Combine le cours du booster scellé et un plancher de valeur attendue",
                      "Combina a cotação do pacote lacrado com um piso de valor esperado"),
                ]),
                ReleaseNoteItem(text: t("카드 판형별 홀로그램과 보관함",
                                         "Finish-specific holograms and collection",
                                         "カード仕様別のホログラムと保管",
                                         "Hologramas y colección según el acabado",
                                         "Hologrammes et collection selon la finition",
                                         "Hologramas e coleção por acabamento"), details: [
                    t("리버스 · 식각 · 샤이니 · 포켓볼 · 마스터볼 등 재질 차이 표현",
                      "Distinct materials for reverse, etched, shiny, Poké Ball, Master Ball and more",
                      "リバース・エッチング・シャイニー・モンスターボール・マスターボールなどの質感を表現",
                      "Materiales distintos para reversa, grabada, shiny, Poké Ball, Master Ball y más",
                      "Matériaux distincts pour reverse, gravée, shiny, Poké Ball, Master Ball et plus",
                      "Materiais distintos para reversa, gravada, shiny, Poké Ball, Master Ball e mais"),
                ]),
            ]),
            ReleaseNote(version: "0.8.0", items: [
                ReleaseNoteItem(text: t("도감 개편 — 모든 팩에 도감이 생겼습니다",
                                         "Dex overhaul — every pack now has one",
                                         "図鑑改編 — すべてのパックに図鑑がつきました",
                                         "Dex renovado: ahora cada sobre tiene uno",
                                         "Dex refondu — chaque booster a le sien",
                                         "Dex reformulado — cada pacote tem o seu"), details: [
                    t("조합 도감 155종 · 전체 277종 추가",
                      "155 theme dexes added, 277 in all",
                      "テーマ図鑑155種 · 全体277種を追加",
                      "155 dex temáticos añadidos, 277 en total",
                      "155 dex thématiques ajoutés, 277 en tout",
                      "155 dex temáticos adicionados, 277 no total"),
                ]),
                ReleaseNoteItem(text: t("도감 보상 개편",
                                         "Dex rewards reworked",
                                         "図鑑報酬を改編",
                                         "Recompensas del dex renovadas",
                                         "Récompenses du dex revues",
                                         "Recompensas do dex reformuladas"), details: [
                    t("신규 보상: 누적 혜택 · 팩 · 팩 할인 쿠폰 · 확정 카드",
                      "New rewards: perks, packs, pack coupons and a granted card",
                      "新しい報酬: 永続効果 · パック · 割引クーポン · 確定カード",
                      "Nuevas recompensas: ventajas, sobres, cupones y carta garantizada",
                      "Nouvelles récompenses : avantages, boosters, coupons et carte garantie",
                      "Novas recompensas: vantagens, pacotes, cupons e carta garantida"),
                ]),
                ReleaseNoteItem(text: t("한도 달성 보너스 팩 조정",
                                         "Limit bonus packs rebalanced",
                                         "上限達成ボーナスパックを調整",
                                         "Sobres por límite reajustados",
                                         "Boosters bonus de quota réajustés",
                                         "Pacotes bônus de limite reajustados"), details: [
                    t("무작위 세트 10팩 → 세트에 따라 1~7팩",
                      "Ten random packs became one to seven, depending on the set",
                      "無作為のセット10パック → セットにより1~7パック",
                      "Diez sobres al azar pasan a ser de 1 a 7 según el set",
                      "Dix boosters au hasard deviennent 1 à 7 selon le set",
                      "Dez pacotes aleatórios viram de 1 a 7 conforme o set"),
                    t("세트마다 팩값이 크게 달라 보상이 튀던 것을 고정",
                      "Pack prices vary hugely between sets, so the payout no longer swings",
                      "セットごとにパック価格が大きく違い、報酬が跳ねていたのを固定",
                      "Los precios varían mucho entre sets; el premio ya no salta",
                      "Les prix varient beaucoup selon les sets ; le gain ne saute plus",
                      "Os preços variam muito entre sets; o prêmio não oscila mais"),
                ]),
                ReleaseNoteItem(text: t("버그 수정",
                                         "Fixes",
                                         "不具合修正",
                                         "Correcciones",
                                         "Corrections",
                                         "Correções"), details: [
                    t("계정을 바꾸면 같은 한도에서 보너스 팩이 다시 지급되던 현상 수정",
                      "Switching accounts could pay bonus packs again for the same limit window",
                      "アカウントを切り替えると同じ上限枠でボーナスパックが再支給される問題を修正",
                      "Cambiar de cuenta podía repetir los sobres de la misma ventana",
                      "Changer de compte pouvait redonner les boosters de la même fenêtre",
                      "Trocar de conta podia repetir os pacotes da mesma janela"),
                ]),
            ]),
            ReleaseNote(version: "0.7.1", items: [
                ReleaseNoteItem(text: t("오리파 공지 보드 문구 정리",
                                         "Tidied the oripa board",
                                         "オリパの案内表示を整理",
                                         "Tablero del Oripa depurado",
                                         "Tableau de l'Oripa allégé",
                                         "Quadro do Oripa limpo"), details: [
                    t("대표 카드 표시와 배수 문구 제거",
                      "Dropped the headline-card label and the multiplier line",
                      "目玉カードの表示と倍率の文言を削除",
                      "Quitados la etiqueta de carta estrella y el multiplicador",
                      "Suppression du libellé carte vedette et du multiplicateur",
                      "Removidos o rótulo de carta principal e o multiplicador"),
                ]),
            ]),
            ReleaseNote(version: "0.7.0", items: [
                ReleaseNoteItem(text: t("오리파 대개편",
                                         "Oripa overhaul",
                                         "オリパ大改編",
                                         "Renovación del Oripa",
                                         "Refonte de l'Oripa",
                                         "Reforma do Oripa"), details: [
                    t("봉투를 직접 골라서 뽑도록 변경",
                      "You now pick the envelope yourself",
                      "封を自分で選んで引く方式に変更",
                      "Ahora eliges el sobre tú mismo",
                      "Tu choisis désormais la pochette",
                      "Agora você escolhe o envelope"),
                    t("박스마다 대표 카드 지정 — 뽑기값의 6배",
                      "Each box gets a headline card, worth 6 pulls",
                      "箱ごとに目玉カードを設定 — 引き値の6倍",
                      "Cada caja tiene carta estrella: 6 tiradas",
                      "Chaque boîte a une carte vedette : 6 tirages",
                      "Cada caixa tem carta principal: 6 tiragens"),
                    t("대표 카드에 따라 박스 규모가 달라짐",
                      "The box scales with its headline card",
                      "目玉カードに応じて箱の規模が変わる",
                      "La caja escala con su carta estrella",
                      "La boîte s'échelonne selon sa vedette",
                      "A caixa escala com sua carta principal"),
                    t("뽑기값 785,100원 → 보통 박스 240,000원 안팎",
                      "785,100 KRW a pull became about 240,000 for a typical box",
                      "引き値 785,100ウォン → 普通の箱は240,000ウォン前後",
                      "De 785 100 KRW a unos 240 000 en una caja típica",
                      "De 785 100 KRW à environ 240 000 pour une boîte type",
                      "De 785.100 KRW para cerca de 240.000 numa caixa típica"),
                    t("100칸 → 40봉투, 기존 박스는 새 박스로 교체",
                      "100 slots became 40 envelopes; a box in progress is replaced",
                      "100枠 → 40封、進行中の箱は新しい箱に交換",
                      "De 100 huecos a 40 sobres; la caja en curso se reemplaza",
                      "De 100 cases à 40 pochettes ; la boîte en cours est remplacée",
                      "De 100 espaços para 40 envelopes; a caixa em curso é trocada"),
                ]),
            ]),
            ReleaseNote(version: "0.6.0", items: [
                ReleaseNoteItem(text: t("카드 등급 세분화",
                                         "Finer card rarities",
                                         "レアリティを細分化",
                                         "Rarezas más detalladas",
                                         "Raretés plus fines",
                                         "Raridades mais detalhadas"), details: [
                    t("10종 → 20종. 나무위키 레어도 문서 기준으로 다시 분류",
                      "10 tiers became 20, reclassified against the community rarity table",
                      "10種から20種へ。コミュニティのレアリティ表に合わせて再分類",
                      "De 10 a 20 niveles, según la tabla de rarezas de la comunidad",
                      "De 10 à 20 niveaux, revus selon la table de raretés de la communauté",
                      "De 10 para 20 níveis, conforme a tabela de raridades da comunidade"),
                    t("HR(레인보우) · K(찬란한) · ACE · S/SSR(샤이니) · PR(프리즘스타) · "
                      + "A(어메이징) · SH(빛나는) · MUR · BWR 추가",
                      "Added HR, K, ACE, S, SSR, PR, A, SH, MUR and BWR",
                      "HR・K・ACE・S・SSR・PR・A・SH・MUR・BWR を追加",
                      "Añadidos HR, K, ACE, S, SSR, PR, A, SH, MUR y BWR",
                      "Ajout de HR, K, ACE, S, SSR, PR, A, SH, MUR et BWR",
                      "Adicionados HR, K, ACE, S, SSR, PR, A, SH, MUR e BWR"),
                    t("카드 상세에 원본 등급 표시 (LV.X · Prime · 골드스타 등)",
                      "The card view now shows its printed rarity (LV.X, Prime, Gold Star…)",
                      "カード詳細に原本のレアリティを表示（LV.X・Prime・ゴールドスターなど）",
                      "La carta muestra su rareza impresa (LV.X, Prime, Estrella dorada…)",
                      "La carte affiche sa rareté imprimée (LV.X, Prime, Étoile dorée…)",
                      "A carta mostra sua raridade impressa (LV.X, Prime, Estrela dourada…)"),
                ]),
                ReleaseNoteItem(text: t("컬렉션 정렬 추가",
                                         "Sort your collection",
                                         "コレクションの並び替えを追加",
                                         "Ordena tu colección",
                                         "Trier ta collection",
                                         "Ordene sua coleção"), details: [
                    t("가격순(기본) · 등급순 · 최근 획득순 · 중복 많은순",
                      "By price (default), rarity, recently added, or most duplicates",
                      "価格順（既定）・レアリティ順・入手が新しい順・重複が多い順",
                      "Por precio (predeterminado), rareza, recientes o repetidas",
                      "Par prix (défaut), rareté, ajouts récents ou doublons",
                      "Por preço (padrão), raridade, recentes ou repetidas"),
                ]),
                ReleaseNoteItem(text: t("카드 상세에 최초 획득 일자 표시",
                                         "Card view shows when you first got it",
                                         "カード詳細に初入手日を表示",
                                         "La carta muestra cuándo la obtuviste",
                                         "La carte indique quand tu l'as obtenue",
                                         "A carta mostra quando você a obteve"), details: [
                    t("이전에 모은 카드는 처음 실행한 날짜로 기록됩니다",
                      "Cards collected before this update are dated to first launch",
                      "以前に集めたカードは初回起動日で記録されます",
                      "Las cartas anteriores quedan con la fecha del primer inicio",
                      "Les cartes déjà collectées prennent la date du premier lancement",
                      "As cartas anteriores ficam com a data da primeira execução"),
                ]),
                ReleaseNoteItem(text: t("버그 수정",
                                         "Fixes",
                                         "不具合修正",
                                         "Correcciones",
                                         "Corrections",
                                         "Correções"), details: [
                    t("「빛나는 전설」의 빛나는 포켓몬 6장이 팩에서 나오지 않던 현상 수정",
                      "Six Shining cards in Shining Legends could never be pulled",
                      "「ひかる伝説」のひかるポケモン6枚が出なかった問題を修正",
                      "Seis cartas Shining de Shining Legends nunca salían",
                      "Six cartes Shining de Légendes Brillantes ne sortaient jamais",
                      "Seis cartas Shining de Shining Legends nunca saíam"),
                    t("가진 팩 목록이 최신 세트부터 보이도록 수정",
                      "Your packs are listed newest set first",
                      "所持パックが新しいセット順に並ぶよう修正",
                      "Tus sobres se listan del set más nuevo",
                      "Tes boosters sont listés du set le plus récent",
                      "Seus pacotes aparecem do set mais novo"),
                    t("오리파 등급 표가 깨져 보이던 현상 수정",
                      "The oripa rarity row no longer overflows",
                      "オリパのレアリティ表が崩れる問題を修正",
                      "La fila de rarezas del oripa ya no se desborda",
                      "La ligne de raretés de l'oripa ne déborde plus",
                      "A linha de raridades do oripa não estoura mais"),
                    t("상단 탭과 상점 탭의 크기가 어긋나던 현상 수정",
                      "The tab row and the shop's picker are the same size again",
                      "上部タブとショップのタブの大きさが揃うよう修正",
                      "La barra de pestañas y el selector de la tienda vuelven a coincidir",
                      "La barre d'onglets et le sélecteur de la boutique s'accordent à nouveau",
                      "A barra de abas e o seletor da loja voltam a combinar"),
                ]),
            ]),
            ReleaseNote(version: "0.5.0", items: [
                ReleaseNoteItem(text: t("전체 팩 추가",
                                         "Every pack is now on sale",
                                         "全パックを追加",
                                         "Todos los sobres a la venta",
                                         "Tous les boosters en vente",
                                         "Todos os pacotes à venda"), details: [
                    t("전체 팩 데이터 추가 / 시세 연동",
                      "Every set added, with live market prices",
                      "全セットのデータと相場を追加",
                      "Todos los sets con precios de mercado",
                      "Tous les sets avec les prix du marché",
                      "Todos os sets com preços de mercado"),
                    t("총 팩 122종류, 카드 17,666개",
                      "122 packs, 17,666 cards",
                      "パック 122種類・カード 17,666枚",
                      "122 sobres, 17,666 cartas",
                      "122 boosters, 17,666 cartes",
                      "122 pacotes, 17,666 cartas"),
                ]),
                ReleaseNoteItem(text: t("팩 정보에서 카드 라인업 확인하는 기능 추가",
                                         "See every card a pack can hold",
                                         "パック情報から収録カードを確認できます",
                                         "Mira todas las cartas que puede traer un sobre",
                                         "Voir toutes les cartes qu'un booster peut contenir",
                                         "Veja todas as cartas que um pacote pode trazer")),
            ]),
            ReleaseNote(version: "0.4.2", items: [
                ReleaseNoteItem(text: t("버그 수정",
                                         "Fixes",
                                         "不具合修正",
                                         "Correcciones",
                                         "Corrections",
                                         "Correções"), details: [
                    t("위젯이 닫히면 기존 뽑기 화면이 날아가는 현상 수정",
                      "Closing the window no longer throws away the pack you were opening",
                      "ウィンドウを閉じても開封中の画面が消えなくなりました",
                      "Cerrar la ventana ya no descarta el sobre que estabas abriendo",
                      "Fermer la fenêtre n'abandonne plus le booster en cours d'ouverture",
                      "Fechar a janela não descarta mais o pacote que você estava abrindo"),
                ]),
            ]),
            ReleaseNote(version: "0.4.1", items: [
                ReleaseNoteItem(text: t("버그 수정",
                                         "Fixes",
                                         "不具合修正",
                                         "Correcciones",
                                         "Corrections",
                                         "Correções"), details: [
                    t("가격이 반올림되어 사용자 경험이 저해되는 현상 수정",
                      "Prices were rounded, so what you saw wasn't what you paid",
                      "価格が丸められて表示と実際の支払いがずれる問題を修正",
                      "Los precios se redondeaban y no coincidían con el cobro",
                      "Les prix étaient arrondis et ne correspondaient pas au débit",
                      "Os preços eram arredondados e não batiam com a cobrança"),
                    t("카드팩 확률표에서 SAR 문구가 줄바뀜되는 현상 수정",
                      "SAR no longer wraps onto two lines in the odds table",
                      "確率表で SAR が2行に折り返される問題を修正",
                      "SAR ya no se parte en dos líneas en la tabla de probabilidades",
                      "SAR ne passe plus à la ligne dans le tableau des probabilités",
                      "SAR não quebra mais em duas linhas na tabela de chances"),
                    t("컬렉션 탭에서 카드가 로딩될 때 덜컹거리는 현상 수정",
                      "The collection no longer stutters while card art loads",
                      "コレクションでカード画像の読み込み中にカクつく問題を修正",
                      "La colección ya no se traba mientras cargan las imágenes",
                      "La collection ne saccade plus pendant le chargement des images",
                      "A coleção não trava mais enquanto as imagens carregam"),
                    t("탭 폭이 좁아보이던 현상 수정",
                      "The tab bar fills the window again",
                      "タブの幅が狭く見える問題を修正",
                      "La barra de pestañas vuelve a ocupar todo el ancho",
                      "La barre d'onglets remplit à nouveau la fenêtre",
                      "A barra de abas volta a ocupar toda a largura"),
                ]),
                ReleaseNoteItem(text: t("한번에 판매 추가",
                                         "Sell in bulk",
                                         "まとめて売る機能を追加",
                                         "Venta en lote",
                                         "Vente en lot",
                                         "Venda em lote"), details: [
                    t("특정 가치 이하의 카드를 전부 판매하는 기능",
                      "Sell every spare card worth up to a price you pick",
                      "指定した金額以下のカードの重複をまとめて売れます",
                      "Vende las repetidas por debajo del precio que elijas",
                      "Vends les doubles sous le prix que tu choisis",
                      "Venda as repetidas abaixo do preço que você escolher"),
                    t("컬렉션 탭에서 사용 가능",
                      "Available from the collection tab",
                      "コレクションタブから使えます",
                      "Disponible en la pestaña de colección",
                      "Disponible dans l'onglet collection",
                      "Disponível na aba de coleção"),
                ]),
                ReleaseNoteItem(text: t("카드깡 마지막 장에 결과보기 버튼 추가",
                                         "A See results button on the last card you open",
                                         "開封の最後の1枚に「結果を見る」ボタンを追加",
                                         "Botón de resultados en la última carta abierta",
                                         "Bouton « Voir les résultats » sur la dernière carte",
                                         "Botão de resultados na última carta aberta")),
                ReleaseNoteItem(text: t("버그 발생으로 인한 사죄의 사료 제공",
                                         "An apology treat for the trouble",
                                         "不具合のおわびにごはんをお配りします",
                                         "Un obsequio de disculpa por las molestias",
                                         "Un cadeau d'excuse pour la gêne",
                                         "Um agrado de desculpas pelo transtorno")),
            ]),
            ReleaseNote(version: "0.4.0", items: [
                ReleaseNoteItem(text: t("시세 연동 대개편",
                                         "Market prices, everywhere",
                                         "相場連動の大改編",
                                         "Precios de mercado en todo",
                                         "Prix du marché partout",
                                         "Preços de mercado em tudo"), details: [
                    t("실제 카드 시세가 카드에 표시됨",
                      "Every card shows its real market price",
                      "カードに実際の相場を表示",
                      "Cada carta muestra su precio real de mercado",
                      "Chaque carte affiche son prix réel du marché",
                      "Cada carta mostra seu preço real de mercado"),
                    t("실제 카드 팩 가격에 맞게 반영",
                      "Pack prices follow the real market",
                      "パック価格を実際の相場に合わせた",
                      "El precio de los sobres sigue el mercado real",
                      "Le prix des boosters suit le marché réel",
                      "O preço dos pacotes segue o mercado real"),
                    t("거래 단위가 토큰 → 원화로 변경",
                      "Prices are shown in won, not tokens",
                      "取引単位をトークンからウォンに変更",
                      "Los precios se muestran en wones, no en tokens",
                      "Les prix sont affichés en wons, plus en tokens",
                      "Os preços aparecem em wones, não em tokens"),
                    t("컬렉션 총 가치 표기",
                      "Your collection's total value in the header",
                      "コレクションの総価値を表示",
                      "Valor total de tu colección en la cabecera",
                      "Valeur totale de ta collection dans l'en-tête",
                      "Valor total da sua coleção no topo"),
                    t("컬렉션 정렬을 카드 가치 순으로 변경",
                      "The collection is sorted by card value",
                      "コレクションをカード価値順に並べ替え",
                      "La colección se ordena por valor de carta",
                      "La collection est triée par valeur de carte",
                      "A coleção é ordenada por valor da carta"),
                    t("도감 난이도는 카드 가치 기준으로 재산정",
                      "Dex difficulty is recalculated from card value",
                      "図鑑の難易度をカード価値基準に再計算",
                      "La dificultad del dex se recalcula por valor de carta",
                      "La difficulté des dex est recalculée par valeur de carte",
                      "A dificuldade do dex é recalculada por valor da carta"),
                ]),
                ReleaseNoteItem(text: t("카드 뽑기 시 카드명과 시세가 함께 표기되도록 UI 추가",
                                         "Opening a pack now shows each card's name and price",
                                         "開封中にカード名と相場を一緒に表示",
                                         "Al abrir un sobre se ve el nombre y el precio de cada carta",
                                         "À l'ouverture, le nom et le prix de chaque carte s'affichent",
                                         "Ao abrir, aparecem o nome e o preço de cada carta"), details: [
                    t("뽑기 완료 시 해당 뽑기에서 나온 카드의 총 가치 표시",
                      "The summary adds up what the pack was worth",
                      "開封結果にそのパックの総価値を表示",
                      "El resumen suma cuánto valía el sobre",
                      "Le résumé additionne la valeur du booster",
                      "O resumo soma quanto o pacote valia"),
                ]),
                ReleaseNoteItem(text: t("컬렉션에서 보유한 카드만 보기 ON/OFF 기능 추가",
                                         "Collection: show only the cards you own, on or off",
                                         "コレクションに「所持カードのみ」の切り替えを追加",
                                         "Colección: mostrar solo tus cartas, activable",
                                         "Collection : n'afficher que tes cartes, activable",
                                         "Coleção: mostrar só suas cartas, com liga/desliga")),
                ReleaseNoteItem(text: t("전반적인 앱 UI 개편",
                                         "The whole interface has been reworked",
                                         "アプリ全体の UI を刷新",
                                         "Toda la interfaz ha sido rediseñada",
                                         "Toute l'interface a été revue",
                                         "Toda a interface foi reformulada")),
            ]),
            ReleaseNote(version: "0.3.3", lines: [
                t("카드깡 시 뒤에 카드 보이도록 UI 수정",
                  "The next card now sits under the one in your hand",
                  "次のカードが手にしているカードの下に見えるように",
                  "La siguiente carta ahora asoma bajo la que tienes",
                  "La carte suivante apparaît sous celle que tu tiens",
                  "A próxima carta agora aparece sob a que você segura"),
                t("오리파 카드깡 시 확인 문구 추가, 가림막 추가",
                  "Oripa asks before drawing, and the card comes out under a cover",
                  "オリパは引く前に確認し、カードは覆いの下から出てくる",
                  "El oripa pregunta antes de tirar y la carta sale bajo una tapa",
                  "L'oripa demande avant de tirer, et la carte sort sous un cache",
                  "O oripa pergunta antes de tirar, e a carta sai sob uma capa"),
                t("카드깡 시 카드 크기가 기존보다 20% 더 커짐",
                  "Cards are about 20% bigger while you open",
                  "開封中のカードが約20%大きく",
                  "Las cartas son un 20% más grandes al abrir",
                  "Les cartes sont environ 20% plus grandes à l'ouverture",
                  "As cartas ficam cerca de 20% maiores na abertura"),
            ]),
            ReleaseNote(version: "0.3.2", lines: [
                t("카드명 한글화",
                  "Korean card names",
                  "カード名を韓国語表記に",
                  "Nombres de cartas en coreano",
                  "Noms de cartes en coréen",
                  "Nomes das cartas em coreano"),
                t("앱에 패치 노트 추가",
                  "Release notes now live in the app",
                  "アプリに更新履歴を追加",
                  "Notas de versión dentro de la app",
                  "Notes de version dans l'app",
                  "Notas de versão dentro do app"),
                t("메뉴바 아이콘이 내 카드로 바뀜 (최애 카드 지정 가능)",
                  "The menu bar icon is now your card — pick a favourite",
                  "メニューバーのアイコンが自分のカードに（お気に入り指定可）",
                  "El icono de la barra de menús ahora es tu carta (elige favorita)",
                  "L'icône de la barre de menus est ta carte (choisis ta favorite)",
                  "O ícone da barra de menus agora é a sua carta (escolha a favorita)"),
                t("카드깡 방식 변경",
                  "Reworked how packs are built",
                  "パックの構成を変更",
                  "Nueva composición de los sobres",
                  "Composition des boosters revue",
                  "Nova composição dos pacotes"),
                t("오리파 뽑기 UI 개선",
                  "Better oripa draw screen",
                  "オリパの抽選画面を改善",
                  "Pantalla de tirada de oripa mejorada",
                  "Écran de tirage oripa amélioré",
                  "Tela de sorteio do oripa melhorada"),
            ]),
            ReleaseNote(version: "0.3.1", lines: [
                t("오리파 뽑기 시 효과 부족한 부분 수정",
                  "Added the missing oripa draw animation",
                  "オリパ抽選時の演出不足を修正",
                  "Se añadió la animación que faltaba al tirar oripa",
                  "Ajout de l'animation manquante au tirage oripa",
                  "Adicionada a animação que faltava no sorteio do oripa"),
                t("업데이트 확인이 느린 현상 수정",
                  "Fixed slow update checks",
                  "アップデート確認が遅い問題を修正",
                  "Se corrigió la lentitud al buscar actualizaciones",
                  "Correction de la lenteur des vérifications de mise à jour",
                  "Corrigida a lentidão na verificação de atualizações"),
            ]),
            ReleaseNote(version: "0.3.0", lines: [
                t("갓팩 추가 (1/300 확률로 갓-팩이 등장)",
                  "God Pack added — 1 in 300 packs",
                  "ゴッドパックを追加（1/300で出現）",
                  "Sobre divino añadido: 1 de cada 300",
                  "God Pack ajouté — 1 booster sur 300",
                  "God Pack adicionado — 1 a cada 300 pacotes"),
                t("오리파 추가",
                  "Oripa added",
                  "オリパを追加",
                  "Oripa añadido",
                  "Oripa ajouté",
                  "Oripa adicionado"),
                t("도감이 난이도순으로 정렬",
                  "Dex now sorts by difficulty",
                  "図鑑を難易度順に並べ替え",
                  "El dex ahora se ordena por dificultad",
                  "Le dex se trie désormais par difficulté",
                  "A dex agora ordena por dificuldade"),
                t("토큰수 표기 편의성 개선 (억/만 단위 추가)",
                  "Token counts are easier to read",
                  "トークン表記を読みやすく（億・万単位）",
                  "Las cifras de tokens se leen mejor",
                  "Les nombres de tokens sont plus lisibles",
                  "Contagens de tokens mais legíveis"),
                t("잔버그 수정",
                  "Minor bug fixes",
                  "細かな不具合を修正",
                  "Correcciones menores",
                  "Corrections mineures",
                  "Correções menores"),
            ]),
        ]
    }
}
