import Foundation

/// 업데이트 항목 하나. 아래에 딸린 세부가 있을 수 있다.
///
/// 큰 개편은 제목 한 줄로는 무엇이 바뀌었는지 알 수 없고, 세부를 같은 층에 늘어놓으면
/// 열 줄이 평평하게 이어져 어디까지가 한 덩이인지 읽히지 않는다.
struct ReleaseNoteItem: Sendable, Equatable {
    let text: String
    var details: [String] = []

    /// 제목과 세부를 합친 전체 문구. 번역 누락 검사가 한 줄씩 훑을 때 쓴다.
    var lines: [String] { [text] + details }
}

/// 한 업데이트에서 바뀐 것.
struct ReleaseNote: Identifiable, Sendable, Equatable {
    let version: String
    let items: [ReleaseNoteItem]
    var id: String { version }

    init(version: String, items: [ReleaseNoteItem]) {
        self.version = version
        self.items = items
    }

    /// 세부가 없는 목록. 예전 업데이트은 전부 이 모양이다.
    init(version: String, lines: [String]) {
        self.init(version: version, items: lines.map { ReleaseNoteItem(text: $0) })
    }
}

/// 업데이트 기록. 새 버전을 내기 전에 여기에 먼저 적는다 —
/// `ReleaseNotesTests` 가 배포 버전에 해당하는 항목이 없으면 실패시킨다.
///
/// 문구는 `L` 이 들고 있어 언어를 따라간다. 목록은 최신이 앞이다.
enum ReleaseNotes {
    /// 지금 돌고 있는 앱의 버전. 없으면 nil — 개발 빌드나 테스트 러너가 그렇다.
    static var runningVersion: String? {
        Bundle.main.object(forInfoDictionaryKey: "CFBundleShortVersionString") as? String
    }

    /// 버전을 숫자 묶음으로 바꾼다. 문자열 비교로는 0.3.10 이 0.3.2 보다 앞이 된다.
    static func ordering(_ version: String) -> [Int] {
        version.split(separator: ".").map { Int($0) ?? 0 }
    }

    /// 최신이 앞인가. 뒤엣것이 앞엣것보다 반드시 작아야 한다.
    static func isDescending(_ notes: [ReleaseNote]) -> Bool {
        zip(notes, notes.dropFirst()).allSatisfy {
            ordering($1.version).lexicographicallyPrecedes(ordering($0.version))
        }
    }
}

extension L {

    var releaseNotes: [ReleaseNote] {
        [
            ReleaseNote(version: "0.7.1", items: [
                ReleaseNoteItem(text: t("오리파 공지 보드 문구 정리",
                                         "Tidied the oripa board",
                                         "オリパの案内表示を整理",
                                         "Tablero del Oripa depurado",
                                         "Tableau de l'Oripa allégé",
                                         "Quadro do Oripa limpo"), details: [
                    t("대표 카드 표시와 배수 문구 제거",
                      "Dropped the headline-card label and the multiplier line",
                      "目玉カードの表示と倍率の文言を削除",
                      "Quitados la etiqueta de carta estrella y el multiplicador",
                      "Suppression du libellé carte vedette et du multiplicateur",
                      "Removidos o rótulo de carta principal e o multiplicador"),
                ]),
            ]),
            ReleaseNote(version: "0.7.0", items: [
                ReleaseNoteItem(text: t("오리파 대개편",
                                         "Oripa overhaul",
                                         "オリパ大改編",
                                         "Renovación del Oripa",
                                         "Refonte de l'Oripa",
                                         "Reforma do Oripa"), details: [
                    t("봉투를 직접 골라서 뽑도록 변경",
                      "You now pick the envelope yourself",
                      "封を自分で選んで引く方式に変更",
                      "Ahora eliges el sobre tú mismo",
                      "Tu choisis désormais la pochette",
                      "Agora você escolhe o envelope"),
                    t("박스마다 대표 카드 지정 — 뽑기값의 6배",
                      "Each box gets a headline card, worth 6 pulls",
                      "箱ごとに目玉カードを設定 — 引き値の6倍",
                      "Cada caja tiene carta estrella: 6 tiradas",
                      "Chaque boîte a une carte vedette : 6 tirages",
                      "Cada caixa tem carta principal: 6 tiragens"),
                    t("대표 카드에 따라 박스 규모가 달라짐",
                      "The box scales with its headline card",
                      "目玉カードに応じて箱の規模が変わる",
                      "La caja escala con su carta estrella",
                      "La boîte s'échelonne selon sa vedette",
                      "A caixa escala com sua carta principal"),
                    t("뽑기값 785,100원 → 보통 박스 240,000원 안팎",
                      "785,100 KRW a pull became about 240,000 for a typical box",
                      "引き値 785,100ウォン → 普通の箱は240,000ウォン前後",
                      "De 785 100 KRW a unos 240 000 en una caja típica",
                      "De 785 100 KRW à environ 240 000 pour une boîte type",
                      "De 785.100 KRW para cerca de 240.000 numa caixa típica"),
                    t("100칸 → 40봉투, 기존 박스는 새 박스로 교체",
                      "100 slots became 40 envelopes; a box in progress is replaced",
                      "100枠 → 40封、進行中の箱は新しい箱に交換",
                      "De 100 huecos a 40 sobres; la caja en curso se reemplaza",
                      "De 100 cases à 40 pochettes ; la boîte en cours est remplacée",
                      "De 100 espaços para 40 envelopes; a caixa em curso é trocada"),
                ]),
            ]),
            ReleaseNote(version: "0.6.0", items: [
                ReleaseNoteItem(text: t("카드 등급 세분화",
                                         "Finer card rarities",
                                         "レアリティを細分化",
                                         "Rarezas más detalladas",
                                         "Raretés plus fines",
                                         "Raridades mais detalhadas"), details: [
                    t("10종 → 20종. 나무위키 레어도 문서 기준으로 다시 분류",
                      "10 tiers became 20, reclassified against the community rarity table",
                      "10種から20種へ。コミュニティのレアリティ表に合わせて再分類",
                      "De 10 a 20 niveles, según la tabla de rarezas de la comunidad",
                      "De 10 à 20 niveaux, revus selon la table de raretés de la communauté",
                      "De 10 para 20 níveis, conforme a tabela de raridades da comunidade"),
                    t("HR(레인보우) · K(찬란한) · ACE · S/SSR(샤이니) · PR(프리즘스타) · "
                      + "A(어메이징) · SH(빛나는) · MUR · BWR 추가",
                      "Added HR, K, ACE, S, SSR, PR, A, SH, MUR and BWR",
                      "HR・K・ACE・S・SSR・PR・A・SH・MUR・BWR を追加",
                      "Añadidos HR, K, ACE, S, SSR, PR, A, SH, MUR y BWR",
                      "Ajout de HR, K, ACE, S, SSR, PR, A, SH, MUR et BWR",
                      "Adicionados HR, K, ACE, S, SSR, PR, A, SH, MUR e BWR"),
                    t("카드 상세에 원본 등급 표시 (LV.X · Prime · 골드스타 등)",
                      "The card view now shows its printed rarity (LV.X, Prime, Gold Star…)",
                      "カード詳細に原本のレアリティを表示（LV.X・Prime・ゴールドスターなど）",
                      "La carta muestra su rareza impresa (LV.X, Prime, Estrella dorada…)",
                      "La carte affiche sa rareté imprimée (LV.X, Prime, Étoile dorée…)",
                      "A carta mostra sua raridade impressa (LV.X, Prime, Estrela dourada…)"),
                ]),
                ReleaseNoteItem(text: t("컬렉션 정렬 추가",
                                         "Sort your collection",
                                         "コレクションの並び替えを追加",
                                         "Ordena tu colección",
                                         "Trier ta collection",
                                         "Ordene sua coleção"), details: [
                    t("가격순(기본) · 등급순 · 최근 획득순 · 중복 많은순",
                      "By price (default), rarity, recently added, or most duplicates",
                      "価格順（既定）・レアリティ順・入手が新しい順・重複が多い順",
                      "Por precio (predeterminado), rareza, recientes o repetidas",
                      "Par prix (défaut), rareté, ajouts récents ou doublons",
                      "Por preço (padrão), raridade, recentes ou repetidas"),
                ]),
                ReleaseNoteItem(text: t("카드 상세에 최초 획득 일자 표시",
                                         "Card view shows when you first got it",
                                         "カード詳細に初入手日を表示",
                                         "La carta muestra cuándo la obtuviste",
                                         "La carte indique quand tu l'as obtenue",
                                         "A carta mostra quando você a obteve"), details: [
                    t("이전에 모은 카드는 처음 실행한 날짜로 기록됩니다",
                      "Cards collected before this update are dated to first launch",
                      "以前に集めたカードは初回起動日で記録されます",
                      "Las cartas anteriores quedan con la fecha del primer inicio",
                      "Les cartes déjà collectées prennent la date du premier lancement",
                      "As cartas anteriores ficam com a data da primeira execução"),
                ]),
                ReleaseNoteItem(text: t("버그 수정",
                                         "Fixes",
                                         "不具合修正",
                                         "Correcciones",
                                         "Corrections",
                                         "Correções"), details: [
                    t("「빛나는 전설」의 빛나는 포켓몬 6장이 팩에서 나오지 않던 현상 수정",
                      "Six Shining cards in Shining Legends could never be pulled",
                      "「ひかる伝説」のひかるポケモン6枚が出なかった問題を修正",
                      "Seis cartas Shining de Shining Legends nunca salían",
                      "Six cartes Shining de Légendes Brillantes ne sortaient jamais",
                      "Seis cartas Shining de Shining Legends nunca saíam"),
                    t("가진 팩 목록이 최신 세트부터 보이도록 수정",
                      "Your packs are listed newest set first",
                      "所持パックが新しいセット順に並ぶよう修正",
                      "Tus sobres se listan del set más nuevo",
                      "Tes boosters sont listés du set le plus récent",
                      "Seus pacotes aparecem do set mais novo"),
                    t("오리파 등급 표가 깨져 보이던 현상 수정",
                      "The oripa rarity row no longer overflows",
                      "オリパのレアリティ表が崩れる問題を修正",
                      "La fila de rarezas del oripa ya no se desborda",
                      "La ligne de raretés de l'oripa ne déborde plus",
                      "A linha de raridades do oripa não estoura mais"),
                    t("상단 탭과 상점 탭의 크기가 어긋나던 현상 수정",
                      "The tab row and the shop's picker are the same size again",
                      "上部タブとショップのタブの大きさが揃うよう修正",
                      "La barra de pestañas y el selector de la tienda vuelven a coincidir",
                      "La barre d'onglets et le sélecteur de la boutique s'accordent à nouveau",
                      "A barra de abas e o seletor da loja voltam a combinar"),
                ]),
            ]),
            ReleaseNote(version: "0.5.0", items: [
                ReleaseNoteItem(text: t("전체 팩 추가",
                                         "Every pack is now on sale",
                                         "全パックを追加",
                                         "Todos los sobres a la venta",
                                         "Tous les boosters en vente",
                                         "Todos os pacotes à venda"), details: [
                    t("전체 팩 데이터 추가 / 시세 연동",
                      "Every set added, with live market prices",
                      "全セットのデータと相場を追加",
                      "Todos los sets con precios de mercado",
                      "Tous les sets avec les prix du marché",
                      "Todos os sets com preços de mercado"),
                    t("총 팩 122종류, 카드 17,666개",
                      "122 packs, 17,666 cards",
                      "パック 122種類・カード 17,666枚",
                      "122 sobres, 17,666 cartas",
                      "122 boosters, 17,666 cartes",
                      "122 pacotes, 17,666 cartas"),
                ]),
                ReleaseNoteItem(text: t("팩 정보에서 카드 라인업 확인하는 기능 추가",
                                         "See every card a pack can hold",
                                         "パック情報から収録カードを確認できます",
                                         "Mira todas las cartas que puede traer un sobre",
                                         "Voir toutes les cartes qu'un booster peut contenir",
                                         "Veja todas as cartas que um pacote pode trazer")),
            ]),
            ReleaseNote(version: "0.4.2", items: [
                ReleaseNoteItem(text: t("버그 수정",
                                         "Fixes",
                                         "不具合修正",
                                         "Correcciones",
                                         "Corrections",
                                         "Correções"), details: [
                    t("위젯이 닫히면 기존 뽑기 화면이 날아가는 현상 수정",
                      "Closing the window no longer throws away the pack you were opening",
                      "ウィンドウを閉じても開封中の画面が消えなくなりました",
                      "Cerrar la ventana ya no descarta el sobre que estabas abriendo",
                      "Fermer la fenêtre n'abandonne plus le booster en cours d'ouverture",
                      "Fechar a janela não descarta mais o pacote que você estava abrindo"),
                ]),
            ]),
            ReleaseNote(version: "0.4.1", items: [
                ReleaseNoteItem(text: t("버그 수정",
                                         "Fixes",
                                         "不具合修正",
                                         "Correcciones",
                                         "Corrections",
                                         "Correções"), details: [
                    t("가격이 반올림되어 사용자 경험이 저해되는 현상 수정",
                      "Prices were rounded, so what you saw wasn't what you paid",
                      "価格が丸められて表示と実際の支払いがずれる問題を修正",
                      "Los precios se redondeaban y no coincidían con el cobro",
                      "Les prix étaient arrondis et ne correspondaient pas au débit",
                      "Os preços eram arredondados e não batiam com a cobrança"),
                    t("카드팩 확률표에서 SAR 문구가 줄바뀜되는 현상 수정",
                      "SAR no longer wraps onto two lines in the odds table",
                      "確率表で SAR が2行に折り返される問題を修正",
                      "SAR ya no se parte en dos líneas en la tabla de probabilidades",
                      "SAR ne passe plus à la ligne dans le tableau des probabilités",
                      "SAR não quebra mais em duas linhas na tabela de chances"),
                    t("컬렉션 탭에서 카드가 로딩될 때 덜컹거리는 현상 수정",
                      "The collection no longer stutters while card art loads",
                      "コレクションでカード画像の読み込み中にカクつく問題を修正",
                      "La colección ya no se traba mientras cargan las imágenes",
                      "La collection ne saccade plus pendant le chargement des images",
                      "A coleção não trava mais enquanto as imagens carregam"),
                    t("탭 폭이 좁아보이던 현상 수정",
                      "The tab bar fills the window again",
                      "タブの幅が狭く見える問題を修正",
                      "La barra de pestañas vuelve a ocupar todo el ancho",
                      "La barre d'onglets remplit à nouveau la fenêtre",
                      "A barra de abas volta a ocupar toda a largura"),
                ]),
                ReleaseNoteItem(text: t("한번에 판매 추가",
                                         "Sell in bulk",
                                         "まとめて売る機能を追加",
                                         "Venta en lote",
                                         "Vente en lot",
                                         "Venda em lote"), details: [
                    t("특정 가치 이하의 카드를 전부 판매하는 기능",
                      "Sell every spare card worth up to a price you pick",
                      "指定した金額以下のカードの重複をまとめて売れます",
                      "Vende las repetidas por debajo del precio que elijas",
                      "Vends les doubles sous le prix que tu choisis",
                      "Venda as repetidas abaixo do preço que você escolher"),
                    t("컬렉션 탭에서 사용 가능",
                      "Available from the collection tab",
                      "コレクションタブから使えます",
                      "Disponible en la pestaña de colección",
                      "Disponible dans l'onglet collection",
                      "Disponível na aba de coleção"),
                ]),
                ReleaseNoteItem(text: t("카드깡 마지막 장에 결과보기 버튼 추가",
                                         "A See results button on the last card you open",
                                         "開封の最後の1枚に「結果を見る」ボタンを追加",
                                         "Botón de resultados en la última carta abierta",
                                         "Bouton « Voir les résultats » sur la dernière carte",
                                         "Botão de resultados na última carta aberta")),
                ReleaseNoteItem(text: t("버그 발생으로 인한 사죄의 사료 제공",
                                         "An apology treat for the trouble",
                                         "不具合のおわびにごはんをお配りします",
                                         "Un obsequio de disculpa por las molestias",
                                         "Un cadeau d'excuse pour la gêne",
                                         "Um agrado de desculpas pelo transtorno")),
            ]),
            ReleaseNote(version: "0.4.0", items: [
                ReleaseNoteItem(text: t("시세 연동 대개편",
                                         "Market prices, everywhere",
                                         "相場連動の大改編",
                                         "Precios de mercado en todo",
                                         "Prix du marché partout",
                                         "Preços de mercado em tudo"), details: [
                    t("실제 카드 시세가 카드에 표시됨",
                      "Every card shows its real market price",
                      "カードに実際の相場を表示",
                      "Cada carta muestra su precio real de mercado",
                      "Chaque carte affiche son prix réel du marché",
                      "Cada carta mostra seu preço real de mercado"),
                    t("실제 카드 팩 가격에 맞게 반영",
                      "Pack prices follow the real market",
                      "パック価格を実際の相場に合わせた",
                      "El precio de los sobres sigue el mercado real",
                      "Le prix des boosters suit le marché réel",
                      "O preço dos pacotes segue o mercado real"),
                    t("거래 단위가 토큰 → 원화로 변경",
                      "Prices are shown in won, not tokens",
                      "取引単位をトークンからウォンに変更",
                      "Los precios se muestran en wones, no en tokens",
                      "Les prix sont affichés en wons, plus en tokens",
                      "Os preços aparecem em wones, não em tokens"),
                    t("컬렉션 총 가치 표기",
                      "Your collection's total value in the header",
                      "コレクションの総価値を表示",
                      "Valor total de tu colección en la cabecera",
                      "Valeur totale de ta collection dans l'en-tête",
                      "Valor total da sua coleção no topo"),
                    t("컬렉션 정렬을 카드 가치 순으로 변경",
                      "The collection is sorted by card value",
                      "コレクションをカード価値順に並べ替え",
                      "La colección se ordena por valor de carta",
                      "La collection est triée par valeur de carte",
                      "A coleção é ordenada por valor da carta"),
                    t("도감 난이도는 카드 가치 기준으로 재산정",
                      "Dex difficulty is recalculated from card value",
                      "図鑑の難易度をカード価値基準に再計算",
                      "La dificultad del dex se recalcula por valor de carta",
                      "La difficulté des dex est recalculée par valeur de carte",
                      "A dificuldade do dex é recalculada por valor da carta"),
                ]),
                ReleaseNoteItem(text: t("카드 뽑기 시 카드명과 시세가 함께 표기되도록 UI 추가",
                                         "Opening a pack now shows each card's name and price",
                                         "開封中にカード名と相場を一緒に表示",
                                         "Al abrir un sobre se ve el nombre y el precio de cada carta",
                                         "À l'ouverture, le nom et le prix de chaque carte s'affichent",
                                         "Ao abrir, aparecem o nome e o preço de cada carta"), details: [
                    t("뽑기 완료 시 해당 뽑기에서 나온 카드의 총 가치 표시",
                      "The summary adds up what the pack was worth",
                      "開封結果にそのパックの総価値を表示",
                      "El resumen suma cuánto valía el sobre",
                      "Le résumé additionne la valeur du booster",
                      "O resumo soma quanto o pacote valia"),
                ]),
                ReleaseNoteItem(text: t("컬렉션에서 보유한 카드만 보기 ON/OFF 기능 추가",
                                         "Collection: show only the cards you own, on or off",
                                         "コレクションに「所持カードのみ」の切り替えを追加",
                                         "Colección: mostrar solo tus cartas, activable",
                                         "Collection : n'afficher que tes cartes, activable",
                                         "Coleção: mostrar só suas cartas, com liga/desliga")),
                ReleaseNoteItem(text: t("전반적인 앱 UI 개편",
                                         "The whole interface has been reworked",
                                         "アプリ全体の UI を刷新",
                                         "Toda la interfaz ha sido rediseñada",
                                         "Toute l'interface a été revue",
                                         "Toda a interface foi reformulada")),
            ]),
            ReleaseNote(version: "0.3.3", lines: [
                t("카드깡 시 뒤에 카드 보이도록 UI 수정",
                  "The next card now sits under the one in your hand",
                  "次のカードが手にしているカードの下に見えるように",
                  "La siguiente carta ahora asoma bajo la que tienes",
                  "La carte suivante apparaît sous celle que tu tiens",
                  "A próxima carta agora aparece sob a que você segura"),
                t("오리파 카드깡 시 확인 문구 추가, 가림막 추가",
                  "Oripa asks before drawing, and the card comes out under a cover",
                  "オリパは引く前に確認し、カードは覆いの下から出てくる",
                  "El oripa pregunta antes de tirar y la carta sale bajo una tapa",
                  "L'oripa demande avant de tirer, et la carte sort sous un cache",
                  "O oripa pergunta antes de tirar, e a carta sai sob uma capa"),
                t("카드깡 시 카드 크기가 기존보다 20% 더 커짐",
                  "Cards are about 20% bigger while you open",
                  "開封中のカードが約20%大きく",
                  "Las cartas son un 20% más grandes al abrir",
                  "Les cartes sont environ 20% plus grandes à l'ouverture",
                  "As cartas ficam cerca de 20% maiores na abertura"),
            ]),
            ReleaseNote(version: "0.3.2", lines: [
                t("카드명 한글화",
                  "Korean card names",
                  "カード名を韓国語表記に",
                  "Nombres de cartas en coreano",
                  "Noms de cartes en coréen",
                  "Nomes das cartas em coreano"),
                t("앱에 패치 노트 추가",
                  "Release notes now live in the app",
                  "アプリに更新履歴を追加",
                  "Notas de versión dentro de la app",
                  "Notes de version dans l'app",
                  "Notas de versão dentro do app"),
                t("메뉴바 아이콘이 내 카드로 바뀜 (최애 카드 지정 가능)",
                  "The menu bar icon is now your card — pick a favourite",
                  "メニューバーのアイコンが自分のカードに（お気に入り指定可）",
                  "El icono de la barra de menús ahora es tu carta (elige favorita)",
                  "L'icône de la barre de menus est ta carte (choisis ta favorite)",
                  "O ícone da barra de menus agora é a sua carta (escolha a favorita)"),
                t("카드깡 방식 변경",
                  "Reworked how packs are built",
                  "パックの構成を変更",
                  "Nueva composición de los sobres",
                  "Composition des boosters revue",
                  "Nova composição dos pacotes"),
                t("오리파 뽑기 UI 개선",
                  "Better oripa draw screen",
                  "オリパの抽選画面を改善",
                  "Pantalla de tirada de oripa mejorada",
                  "Écran de tirage oripa amélioré",
                  "Tela de sorteio do oripa melhorada"),
            ]),
            ReleaseNote(version: "0.3.1", lines: [
                t("오리파 뽑기 시 효과 부족한 부분 수정",
                  "Added the missing oripa draw animation",
                  "オリパ抽選時の演出不足を修正",
                  "Se añadió la animación que faltaba al tirar oripa",
                  "Ajout de l'animation manquante au tirage oripa",
                  "Adicionada a animação que faltava no sorteio do oripa"),
                t("업데이트 확인이 느린 현상 수정",
                  "Fixed slow update checks",
                  "アップデート確認が遅い問題を修正",
                  "Se corrigió la lentitud al buscar actualizaciones",
                  "Correction de la lenteur des vérifications de mise à jour",
                  "Corrigida a lentidão na verificação de atualizações"),
            ]),
            ReleaseNote(version: "0.3.0", lines: [
                t("갓팩 추가 (1/300 확률로 갓-팩이 등장)",
                  "God Pack added — 1 in 300 packs",
                  "ゴッドパックを追加（1/300で出現）",
                  "Sobre divino añadido: 1 de cada 300",
                  "God Pack ajouté — 1 booster sur 300",
                  "God Pack adicionado — 1 a cada 300 pacotes"),
                t("오리파 추가",
                  "Oripa added",
                  "オリパを追加",
                  "Oripa añadido",
                  "Oripa ajouté",
                  "Oripa adicionado"),
                t("도감이 난이도순으로 정렬",
                  "Dex now sorts by difficulty",
                  "図鑑を難易度順に並べ替え",
                  "El dex ahora se ordena por dificultad",
                  "Le dex se trie désormais par difficulté",
                  "A dex agora ordena por dificuldade"),
                t("토큰수 표기 편의성 개선 (억/만 단위 추가)",
                  "Token counts are easier to read",
                  "トークン表記を読みやすく（億・万単位）",
                  "Las cifras de tokens se leen mejor",
                  "Les nombres de tokens sont plus lisibles",
                  "Contagens de tokens mais legíveis"),
                t("잔버그 수정",
                  "Minor bug fixes",
                  "細かな不具合を修正",
                  "Correcciones menores",
                  "Corrections mineures",
                  "Correções menores"),
            ]),
        ]
    }
}
